
GET http://localhost:8080/api/users

###
POST http://localhost:8080/api/users/
content-type: application/json

{
    "name": "John Mayer4",
    "email": "email4@email.com"
   
}

###
PUT http://localhost:8080/api/users/64ee67eabe7a75844a85b0ba
content-type: application/json

{
    "name": "J2ohn Mayer 21",
    "email": "2email2@email.com"
   
}

###
DELETE http://localhost:8080/api/users/64ee67eabe7a75844a85b0ba
